package com.tracecirclebackend.constants;

public enum Roles {

	SUPER_ADMIN, 
	MANUFACTUROR_ADMMIN, 
	PRODUCT_CREATOR,
	SUPPLIER_ADMIN,
	SUPPLIER_DATA_ENTRY, 
	LOGITICS_ADMIN,
	WAREHOUSE_UPDATATOR,
	LOGISTIC_UPDATOR,
	RETAILER_ADMIN,
	RETAILOR_UPDATOR,
	RECYCLE_ADMIN
}
