package com.tracecirclebackend.constants;

public enum Roles {

	SUPER_ADMIN, 
	MANUFACTUROR_ADMMIN, 
	PRODUCT_CREATOR,
	PRODUCT_APPROVER,
	SUPPLIER_ADMIN,
	SUPPLIER_DATA_ENTRY, 
	LOGITICS_ADMIN,
	LOGISTIC_COORDINATOR,
	DELIVERY_OPERATOR,
	RETAILER_ADMIN,
	INVENTORY_MANAGER,
	RECYCLE_ADMIN
}
